= Sigong - Temporary File Sharing
임시 파일 공유 API

:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 1
:sectlinks:

[[file-upload]]
== POST : /api/v1/file
=== 파일 업로드

해당 API를 통해 파일을 업로드하고, 해당 파일을 조회,삭제,다운로드 할 수 있는 임의의 32자리 문자열 코드를 발급받습니다.

해당 코드는 10분(기본 설정)간 유지되며, 해당 코드를 통해 파일을 다운로드 받거나, API를 사용하면,
코드가 소멸됩니다! _(코드로 파일 정보를 조회하는 것은 코드가 소멸되지 않습니다!)_

파일 업로드시 바이러스 검사를 수행하며, 바이러스 의심파일을 업로드할 경우 일시적으로 서비스 이용이 거부됩니다..

또한 단기간에 많은 파일을 업로드할 경우에도 일시적으로 파일 업로드가 거부될 수 있습니다.(조회 및 다운로드에는 문제가 없습니다!)

업로드할 수 있는 파일 규격은 아래와 같습니다.

[cols="1,1"]
|===
|최대 파일 크기
|50MB

|파일 확장자명
|가본 설정"pdf", "ppt", "pptx", "hwp", "csv", "xlsx" (_홈페이지의 도움말을 참조하세요_)
|===
operation::file-upload[snippets='response-fields,response-body,http-request,http-response,']

[[file-get-info]]
== GET: /api/v1/file/{downloadCode}
=== 파일 정보 조회

해당 API를 통해 파일 정보를 조회할 수 있습니다.

_(정보 조회시에는 코드가 소멸되지 않습니다!)_

operation::file-get-info[snippets='path-parameters,response-fields,response-body,http-request,http-response,']

[[file-revoke]]
== DELETE: /api/v1/file/{downloadCode}
=== 파일 삭제 및 코드 소멸

해당 API를 사용하면, 해당 코드를 소멸시킵니다.

_(주의! 한번 소멸된 코드는 다시 복구할 수 없습니다! 신중하게 사용하세요)_

operation::file-revoke[snippets='path-parameters,response-fields,response-body,http-request,http-response,']

[[file-download]]
== GET: /api/v1/file/{downloadCode}/download
=== 파일 다운로드 및 코드 소멸

해당 API를 사용하면, 해당 코드에 해당하는 파일을 다운로드합니다.

_(다운로드 이후, 해당 파일과 코드는 삭제되며 복구할 수 없습니다!)_

operation::file-download[snippets='path-parameters,http-request,http-response,']
